// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDag93FMBVY7e-H1ofUu3LoyKjFh1Lz7Ys',
    appId: '1:962957337275:web:9d973a7002f90899f53f9e',
    messagingSenderId: '962957337275',
    projectId: 'wandastockapp',
    authDomain: 'wandastockapp.firebaseapp.com',
    storageBucket: 'wandastockapp.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBH4yHakh8nS993JVVhw7JXLVn3SlRAKyU',
    appId: '1:962957337275:android:2bef221f3e64014bf53f9e',
    messagingSenderId: '962957337275',
    projectId: 'wandastockapp',
    storageBucket: 'wandastockapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzMsMHGmwslZnpu_uDQcO0pXiDfyJydio',
    appId: '1:962957337275:ios:d4490243ebcafadcf53f9e',
    messagingSenderId: '962957337275',
    projectId: 'wandastockapp',
    storageBucket: 'wandastockapp.firebasestorage.app',
    iosBundleId: 'com.example.wandastock',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDzMsMHGmwslZnpu_uDQcO0pXiDfyJydio',
    appId: '1:962957337275:ios:d4490243ebcafadcf53f9e',
    messagingSenderId: '962957337275',
    projectId: 'wandastockapp',
    storageBucket: 'wandastockapp.firebasestorage.app',
    iosBundleId: 'com.example.wandastock',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDag93FMBVY7e-H1ofUu3LoyKjFh1Lz7Ys',
    appId: '1:962957337275:web:a345ed59fc8af966f53f9e',
    messagingSenderId: '962957337275',
    projectId: 'wandastockapp',
    authDomain: 'wandastockapp.firebaseapp.com',
    storageBucket: 'wandastockapp.firebasestorage.app',
  );
}
